### ISSUE TITLE
Extracting 3D joints from armature_keypoints

### ISSUE THREAD

**Issue by isendel11** [toinfinityai/InfiniteRep#2]
Hi,

I am trying to plot the 3D skeletons in the dataset ground-truth but I am having some troubles extracting the keypoints (x,y) in meters from the armature_keypoints data structure. Given that (x, y) are in image pixel coordinates and z is in meters, in order to plot everything in a 3D plot (e.g. using matplotlib) I would need to also obtain x,y in meters. I don't believe there is camera information (full extrinsics and intrinsics) in order to directly project the pixel coordinates to meters, right?
Has it something to do with the underlying SMPL-X model? I have never used SMPL before so if that's the case, would you be able to point me to some resource I can look into to do this conversion (bonus points if it has some snippet of code I could cop..ehm, get inspiration from)?

Thanks!

**Comment by aweitz** [comment]
Thanks for the inquiry! Unfortunately, the currently released dataset does not contain the global XYZ locations for each keypoint (or the camera extrinsics to enable their calculation). We will consider adding them to the dataset at a later date. In the meantime, feel free to send an email to info@toinfinity.ai with your needs or [sign up](https://medium.com/infinity-ai/infinity-api-82149d21c87c) for our beta API (which provides the 3D keypoints of interest), as there may be other ways we can help in the short term.
