### ISSUE TITLE
`left_ear`, `right_ear` keypoints

### ISSUE THREAD

**Issue by fan23j** [toinfinityai/InfiniteRep#3]
Hi InfinityAI team, I was exploring your API (fantastic work btw) and InfiniteRep dataset when I noticed that the `left_ear` and `right_ear` keypoints seem to always be {x:0,y:0,vis:0}. 

Some examples from the dataset:
![armraise_000009_image4](https://user-images.githubusercontent.com/54330861/177245098-08da94b7-06a6-425b-b1e5-2291a6c63e1a.jpg)
![bicyclecrunch_000095_image3](https://user-images.githubusercontent.com/54330861/177245109-deede217-6e6e-4fad-8ab3-7d54fd7b62c9.jpg)

The API seems to generate label the ears at (0,0) as well.

**Comment by aweitz** [comment]
Thanks for the question! Information for these keypoints (`left_ear` + `right_ear`) can be found in the`vertex_keypoints` data structure of the JSON file returned by the API. These were added after InfiniteRep's release.
